# Generated by Django 6.0.2 on 2026-02-24 06:18

import django.contrib.auth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Foydalanuvchi nomi')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Familiya')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('is_worker', models.BooleanField(default=False, help_text="Agar foydalanuvchi ishchi bo'lsa, belgilang.", verbose_name='Ishchi')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Ro‘yxatdan o‘tgan sana')),
                ('is_staff', models.BooleanField(default=False, help_text="Foydalanuvchi admin paneliga kirishi mumkin bo'lsa, belgilang.", verbose_name='Admin panel')),
                ('is_active', models.BooleanField(default=True, help_text="Agar foydalanuvchi faol bo'lsa, belgilang.", verbose_name='Faol')),
                ('is_superuser', models.BooleanField(default=False, help_text="Foydalanuvchining barcha ruxsatlari bor bo'lsa, belgilang.", verbose_name='Super foydalanuvchi  ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi ',
                'verbose_name_plural': 'Foydalanuvchilar ',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
