# Generated by Django 6.0.1 on 2026-02-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='worker_status',
            new_name='is_worker',
        ),
    ]
