# Generated by Django 6.0.1 on 2026-01-20 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('position', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('salary_type', models.CharField(choices=[('fixed', 'Belgilangan'), ('hourly', 'Soatbay'), ('piecework', 'Parchabay')], default='fixed', max_length=50, verbose_name='Maosh turi')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Asosiy maosh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('earned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Topilgan summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan summa")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='employees.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Balans',
                'verbose_name_plural': 'Balanslar',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('month', models.IntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], verbose_name='Oy')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami topilgan')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Jami to'langan")),
                ('net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qolgan balans')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Yopilgan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_statistics', to='employees.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Balans statistikasi',
                'verbose_name_plural': 'Balans statistikasi',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
