# Generated by Django 6.0.1 on 2026-01-26 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Полное имя')),
                ('position', models.CharField(max_length=100, verbose_name='Позиция')),
                ('salary_type', models.CharField(choices=[('fixed', 'Фиксированная'), ('hourly', 'Почасовая'), ('piecework', 'Сдельная')], default='fixed', max_length=50, verbose_name='Вид зарплаты')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Базовая зарплата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': '1. Сотрудник',
                'verbose_name_plural': '1. Сотрудники',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('earned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Topilgan summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan summa")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='employees.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': '2. Баланс',
                'verbose_name_plural': '2. Балансы',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthBalanceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('month', models.IntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], verbose_name='Oy')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami topilgan')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Jami to'langan")),
                ('net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Oy bo'yicha qoldig'i")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_balance_statistics', to='employees.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': '3. Статистика за месяц',
                'verbose_name_plural': '3. Статистика за месяц',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='YearlyBalanceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Yil bo'yicha jami topilgan")),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Yil bo'yicha jami to'langan")),
                ('net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Yil bo'yicha qoldig'i")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_balance_statistics', to='employees.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': '4. Статистика за год',
                'verbose_name_plural': '4. Статистика за год',
                'ordering': ['-year', 'employee__full_name'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
