# Generated by Django 6.0.1 on 2026-01-26 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '2. Баланс', 'verbose_name_plural': '2. Балансы'},
        ),
        migrations.AlterModelOptions(
            name='balancestatistics',
            options={'ordering': ['-year', '-month'], 'verbose_name': '3. Статистика баланса', 'verbose_name_plural': '3. Статистика баланса'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at'], 'verbose_name': '1. Сотрудник', 'verbose_name_plural': '1. Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='balancestatistics',
            name='is_closed',
        ),
        migrations.AlterField(
            model_name='balancestatistics',
            name='net_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Oy bo'yicha qoldig'i"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Базовая зарплата'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная'), ('hourly', 'Почасовая'), ('piecework', 'Сдельная')], default='fixed', max_length=50, verbose_name='Вид зарплаты'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('employee', 'date')},
        ),
    ]
