# Generated by Django 6.0.1 on 2026-01-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPerformanceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('month', models.IntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], verbose_name='Oy')),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ijara')),
                ('electricity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elektroenergiya')),
                ('gas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gaz')),
                ('water', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Suv')),
                ('salaries', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Maoshlar')),
                ('machine_equipment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mashina va uskunalar')),
                ('tools_equipment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Asboblar va uskunalar')),
                ('staff_food', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Xodimlar uchun ovqat')),
            ],
            options={
                'verbose_name': "Moliya ko'rsatkichi",
                'verbose_name_plural': "Moliya ko'rsatkichlari",
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
