# Generated by Django 6.0.1 on 2026-01-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialperformanceindicator',
            options={'ordering': ['-year', '-month'], 'verbose_name': '1. Финансовый показатель', 'verbose_name_plural': '1. Финансовые показатели'},
        ),
    ]
