# Generated by Django 6.0.1 on 2026-01-20 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('income_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kirim summasi')),
                ('expense_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chiqim summasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kirim va chiqim',
                'verbose_name_plural': 'Kirim va chiqimlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeExpenseStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('month', models.IntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], verbose_name='Oy')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami kirim')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami chiqim')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Foyda')),
            ],
            options={
                'verbose_name': 'Kirim va chiqim statistikasi',
                'verbose_name_plural': 'Kirim va chiqim statistikasi',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
