# Generated by Django 6.0.1 on 2026-01-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomeexpense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '1. Доходы и расходы', 'verbose_name_plural': '1. Доходы и расходы'},
        ),
        migrations.AlterModelOptions(
            name='incomeexpensestatistics',
            options={'ordering': ['-year', '-month'], 'verbose_name': '2. Статистика доходов и расходов', 'verbose_name_plural': '2. Статистика доходов и расходов'},
        ),
    ]
