# Generated by Django 6.0.2 on 2026-02-24 06:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Umumiy summa')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Xarajat ',
                'verbose_name_plural': 'Xarajatlar ',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': '[ Oziq-ovqat elementi ] ',
                'verbose_name_plural': '[ Oziq-ovqat elementlari ] ',
            },
        ),
        migrations.CreateModel(
            name='FoodProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_product_name', models.CharField(max_length=255, verbose_name='Oziq-ovqat nomi')),
                ('measurement_unit', models.CharField(blank=True, max_length=64, verbose_name="O'lchov birligi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Oziq-ovqat ',
                'verbose_name_plural': 'Oziq-ovqatlar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': '[ Xom-ashyo elementi ] ',
                'verbose_name_plural': '[ Xom-ashyo elementlari ] ',
            },
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_material_name', models.CharField(max_length=255, verbose_name='Xom-ashyo nomi')),
                ('measurement_unit', models.CharField(blank=True, max_length=64, verbose_name="O'lchov birligi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Xom-ashyo ',
                'verbose_name_plural': 'Xom-ashyolar ',
                'ordering': ['-created_at'],
            },
        ),
    ]
