# Generated by Django 6.0.2 on 2026-02-19 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='expenses.expenses'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.foodproducts'),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', to='expenses.expenses'),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.rawmaterials'),
        ),
    ]
