# Generated by Django 6.0.2 on 2026-02-24 06:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Ismi va Familiyasi')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Lavozimi')),
                ('salary_type', models.CharField(blank=True, max_length=50, verbose_name='Maosh turi')),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Asosiy maosh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Ishchi ',
                'verbose_name_plural': 'Ishchilar ',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('total_earned_salary', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Kunlik topilgan maosh')),
                ('total_paid_salary', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="Kunlik to'langan maosh")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Kunlik maosh ',
                'verbose_name_plural': 'Kunlik maoshlar ',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Ishlab topilgan summa')),
                ('earned_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ishlab topilgan summa uchun izoh')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="To'langan summa")),
                ('paid_note', models.CharField(blank=True, max_length=255, null=True, verbose_name="To'langan summa uchun izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': '[ Kunlik maosh elementi ] ',
                'verbose_name_plural': '[ Kunlik maosh elementlari ] ',
                'ordering': ['-salary__date', 'created_at'],
            },
        ),
    ]
