# Generated by Django 6.0.2 on 2026-02-24 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='salary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan yaratilgan'),
        ),
        migrations.AddField(
            model_name='salaryitem',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_items', to='salary.employee', verbose_name='Ishchi'),
        ),
        migrations.AddField(
            model_name='salaryitem',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_items', to='salary.salary', verbose_name='Kunlik maosh'),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('created_by', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='salaryitem',
            unique_together={('salary', 'employee')},
        ),
    ]
