# Generated by Django 6.0.2 on 2026-02-20 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='earned_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Заработанная сумма'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='earned_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание заработанной суммы'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_items', to='salary.employee', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Выплаченная сумма'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='paid_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание выплаченной суммы'),
        ),
        migrations.AlterField(
            model_name='salaryitem',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_items', to='salary.salary', verbose_name='Зарплата'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryitem',
            unique_together={('salary', 'employee')},
        ),
    ]
