# Generated by Django 6.0.2 on 2026-02-20 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='earned_amount',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='earned_note',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='paid_note',
        ),
        migrations.AddField(
            model_name='salary',
            name='total_earned_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_paid_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.CreateModel(
            name='SalaryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('earned_note', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('paid_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_items', to='salary.employee')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_items', to='salary.salary')),
            ],
            options={
                'ordering': ['-salary__date', 'created_at'],
            },
        ),
    ]
