# Generated by Django 6.0.2 on 2026-02-24 06:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('sign', models.CharField(blank=True, max_length=255, verbose_name='Belgisi')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Telefon raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Xaridor ',
                'verbose_name_plural': 'Xaridorlar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('measurement_unit', models.CharField(blank=True, max_length=64, verbose_name="O'lchov birligi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Mahsulot ',
                'verbose_name_plural': 'Mahsulotlar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Jami narx')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Savdo ',
                'verbose_name_plural': 'Savdolar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Miqdor')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Narx')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Jami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': '[ Savdo elementi ] ',
                'verbose_name_plural': '[ Savdo elementlari ] ',
            },
        ),
    ]
