# Generated by Django 6.0.2 on 2026-02-14 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyer', 'verbose_name_plural': 'Buyers'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='olchov_birligi',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mahsulot_nomi',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='umumiy_sotuv',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='xaridor',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='narxi',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='soni',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
