# Generated by Django 6.0.2 on 2026-02-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem_order_status_saleitem_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSaleItem',
            fields=[
            ],
            options={
                'verbose_name': 'Yopilmagan zakaz',
                'verbose_name_plural': 'Yopilmagan zakazlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.saleitem',),
        ),
        migrations.CreateModel(
            name='UnpaidSaleItem',
            fields=[
            ],
            options={
                'verbose_name': "To'lanmagan zakaz",
                'verbose_name_plural': "To'lanmagan zakazlar",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.saleitem',),
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Zakaz ', 'verbose_name_plural': 'Zakazlar '},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': '[ Zakaz elementi ] ', 'verbose_name_plural': '[ Zakaz elementlari ] '},
        ),
    ]
