# Generated by Django 6.0.2 on 2026-02-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_opensaleitem_unpaidsaleitem_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='buyers_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="Xaridor to'lagan summa"),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='order_status',
            field=models.CharField(choices=[('open', 'Jarayonda'), ('closed', 'Yopilgan')], default='open', max_length=10, verbose_name='Zakaz holati'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', "To'lanmagan"), ('partial', 'Qisman'), ('paid', "To'langan")], default='unpaid', max_length=10, verbose_name="To'lov holati"),
        ),
    ]
